server:
  port: 8088

spring:
  application:
    name: myWeb-server

#  profiles:
#    active: dev

  main:
    allow-circular-references: true

#  datasource:
#    druid:
#      driver-class-name: ${myWeb.datasource.driver-class-name}
#      url: jdbc:mysql://${myWeb.datasource.host}:${myWeb.datasource.port}/${myWeb.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: ${myWeb.datasource.username}
#      password: ${myWeb.datasource.password}
  datasource:
    #驱动名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接数据库
    url: jdbc:mysql://localhost:3306/myWeb
    #数据库用户名
    username: root
    #数据库密码
    password: yw248946.

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    map-underscore-to-camel-case: true
